server:
  port: 9100

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
      client:
        registration:
          authclient:              # <-- единое имя registrationId
            client-id: ${SERVICE_A_AUTHCLIENT_ID:client-a}
            client-secret: ${SERVICE_A_AUTHCLIENT_SECRET:secretA}
            authorization-grant-type: client_credentials
            scope: api.read
        provider:
          authclient:
            token-uri: http://localhost:9000/oauth2/token

app:
  peers:
    service-b-url: http://localhost:9200
  oauth2:
    registration-id: authclient   # <- дефолтное имя, используем в WebClientConfig
