server:
  port: 8444
  ssl:
    enabled: true
    key-store: classpath:keystore/service-a.p12
    key-store-password: ${KEYSTORE_PASSWORD}
    key-alias: service-a

spring:
  security:
    oauth2:
      client:
        registration:
          service-b:                     # регистрация клиента для вызова Service B
            authorization-grant-type: client_credentials
            client-id: service-a-client   # client_id, предварительно зарегистрированный на Auth Server
            client-secret: ${SERVICE_A_SECRET}
        provider:
          service-b:
            token-uri: https://auth-server:9443/oauth2/token  # URL получения токена у Auth Server